package api

// russell2000Universe contains approximately 2000 US mid/small-cap stocks.
// Represents the next tier of US equities by market cap after Russell 1000.
// Sourced from NASDAQ screener data, filtered for US equities.
var russell2000Universe = map[string]string{
	"HWC": "Financials",
	"TMHC": "Consumer Discretionary",
	"OZK": "Financials",
	"MATX": "Consumer Discretionary",
	"BC": "Industrials",
	"IRDM": "Communication Services",
	"HOMB": "Financials",
	"CRC": "Energy",
	"AUB": "Financials",
	"MTG": "Financials",
	"ADT": "Consumer Discretionary",
	"MARA": "Information Technology",
	"CWST": "Utilities",
	"CGON": "Health Care",
	"MCY": "Financials",
	"VCTR": "Financials",
	"LPX": "Materials",
	"HASI": "Financials",
	"PSMT": "Consumer Discretionary",
	"MC": "Financials",
	"LYFT": "Consumer Discretionary",
	"DLB": "Other",
	"SIGI": "Financials",
	"GOLF": "Consumer Discretionary",
	"ALK": "Consumer Discretionary",
	"MUR": "Energy",
	"BOOT": "Consumer Discretionary",
	"ACHR": "Industrials",
	"RITM": "Real Estate",
	"WTM": "Financials",
	"CHH": "Consumer Discretionary",
	"RDW": "Industrials",
	"RUSHB": "Consumer Discretionary",
	"BCPC": "Industrials",
	"GNTX": "Consumer Discretionary",
	"MGY": "Energy",
	"NAVN": "Information Technology",
	"PECO": "Real Estate",
	"SBRA": "Real Estate",
	"ALH": "Industrials",
	"DUOL": "Information Technology",
	"SEI": "Consumer Discretionary",
	"DIOD": "Information Technology",
	"OTF": "Other",
	"ZETA": "Information Technology",
	"UWMC": "Financials",
	"BGC": "Financials",
	"IEP": "Consumer Discretionary",
	"XMTR": "Consumer Discretionary",
	"OLLI": "Consumer Discretionary",
	"WEX": "Consumer Discretionary",
	"IPGP": "Information Technology",
	"DNTH": "Health Care",
	"OGS": "Utilities",
	"AX": "Financials",
	"SXT": "Industrials",
	"VSEC": "Consumer Discretionary",
	"GBTG": "Consumer Discretionary",
	"LBRDK": "Communication Services",
	"SITE": "Consumer Discretionary",
	"SR": "Utilities",
	"LBRDA": "Communication Services",
	"HESM": "Energy",
	"CWEN": "Utilities",
	"SON": "Consumer Discretionary",
	"OPEN": "Financials",
	"PAGP": "Energy",
	"HRB": "Consumer Discretionary",
	"POWI": "Information Technology",
	"UNF": "Consumer Discretionary",
	"GHC": "Real Estate",
	"SEB": "Industrials",
	"CNX": "Energy",
	"SPHR": "Consumer Discretionary",
	"HLNE": "Financials",
	"ACLS": "Information Technology",
	"PI": "Information Technology",
	"MTN": "Consumer Discretionary",
	"MAIN": "Financials",
	"REZI": "Industrials",
	"GTLB": "Information Technology",
	"LBRT": "Energy",
	"CNR": "Energy",
	"RLI": "Financials",
	"VSCO": "Consumer Discretionary",
	"CAI": "Health Care",
	"PBF": "Energy",
	"LGND": "Health Care",
	"FBIN": "Materials",
	"FFIN": "Financials",
	"WSC": "Industrials",
	"NNI": "Financials",
	"MKTX": "Financials",
	"WHD": "Consumer Discretionary",
	"MRP": "Financials",
	"FCN": "Consumer Discretionary",
	"REYN": "Consumer Discretionary",
	"CLSK": "Financials",
	"CSW": "Industrials",
	"UFPI": "Materials",
	"MTRN": "Industrials",
	"ASB": "Financials",
	"NTSK": "Information Technology",
	"RDN": "Financials",
	"EBC": "Financials",
	"HRI": "Industrials",
	"OCTV": "Other",
	"AIR": "Industrials",
	"CVLT": "Information Technology",
	"AQN": "Utilities",
	"LAUR": "Real Estate",
	"MIAX": "Financials",
	"CBT": "Industrials",
	"COLD": "Real Estate",
	"IBOC": "Financials",
	"MDU": "Industrials",
	"BLLN": "Health Care",
	"SHC": "Health Care",
	"PFSI": "Financials",
	"TDS": "Communication Services",
	"SAIC": "Information Technology",
	"KNF": "Industrials",
	"LASR": "Information Technology",
	"PVH": "Industrials",
	"LMND": "Financials",
	"SMR": "Industrials",
	"EXLS": "Consumer Discretionary",
	"TVTX": "Health Care",
	"TFSL": "Financials",
	"EPR": "Real Estate",
	"COCO": "Consumer Staples",
	"AD": "Communication Services",
	"KVYO": "Information Technology",
	"CUZ": "Real Estate",
	"BCO": "Industrials",
	"TREX": "Materials",
	"OLED": "Information Technology",
	"FELE": "Consumer Discretionary",
	"MTH": "Consumer Discretionary",
	"POST": "Consumer Staples",
	"KBR": "Industrials",
	"FTDR": "Consumer Discretionary",
	"NWE": "Utilities",
	"VVV": "Industrials",
	"TCBI": "Financials",
	"RDNT": "Health Care",
	"MAT": "Consumer Discretionary",
	"FRMI": "Real Estate",
	"CNO": "Financials",
	"ACIW": "Information Technology",
	"TWST": "Health Care",
	"WING": "Consumer Discretionary",
	"PTEN": "Energy",
	"MIR": "Industrials",
	"RXO": "Consumer Discretionary",
	"TNL": "Consumer Discretionary",
	"HNGE": "Information Technology",
	"SFBS": "Financials",
	"BETA": "Industrials",
	"THO": "Industrials",
	"RELY": "Consumer Discretionary",
	"FHI": "Financials",
	"SKT": "Real Estate",
	"AZZ": "Industrials",
	"PLNT": "Consumer Discretionary",
	"USAC": "Utilities",
	"HGV": "Consumer Discretionary",
	"CVCO": "Consumer Discretionary",
	"AMRX": "Health Care",
	"SLM": "Financials",
	"RUM": "Information Technology",
	"FULT": "Financials",
	"CVSA": "Real Estate",
	"BDC": "Industrials",
	"BBWI": "Consumer Discretionary",
	"KTB": "Industrials",
	"PDI": "Financials",
	"VNT": "Industrials",
	"BRC": "Consumer Discretionary",
	"GFF": "Industrials",
	"AMBA": "Information Technology",
	"SLGN": "Industrials",
	"SKY": "Consumer Discretionary",
	"CRK": "Energy",
	"SEZL": "Financials",
	"KRC": "Real Estate",
	"LOPE": "Real Estate",
	"OPLN": "Consumer Discretionary",
	"PII": "Consumer Discretionary",
	"MWA": "Industrials",
	"UCB": "Financials",
	"ENVA": "Financials",
	"FLNC": "Other",
	"DAN": "Consumer Discretionary",
	"UCTT": "Information Technology",
	"KNSA": "Health Care",
	"LRN": "Real Estate",
	"CRGY": "Energy",
	"ATMU": "Consumer Discretionary",
	"BNL": "Real Estate",
	"GPI": "Consumer Discretionary",
	"IRT": "Real Estate",
	"TPC": "Consumer Discretionary",
	"DOCS": "Information Technology",
	"NVST": "Health Care",
	"CATY": "Financials",
	"HHH": "Real Estate",
	"CPRX": "Health Care",
	"VCYT": "Health Care",
	"INDB": "Financials",
	"OII": "Energy",
	"CII": "Financials",
	"KAI": "Industrials",
	"HP": "Energy",
	"MMSI": "Health Care",
	"INSW": "Consumer Discretionary",
	"IRTC": "Health Care",
	"CRNX": "Health Care",
	"ERAS": "Health Care",
	"RUN": "Other",
	"EE": "Utilities",
	"WSFS": "Financials",
	"RNST": "Financials",
	"VKTX": "Health Care",
	"DORM": "Consumer Discretionary",
	"WAY": "Information Technology",
	"TDW": "Consumer Discretionary",
	"BANF": "Financials",
	"ITRI": "Industrials",
	"SOUN": "Information Technology",
	"ACAD": "Health Care",
	"JOE": "Real Estate",
	"CDP": "Real Estate",
	"STUB": "Consumer Discretionary",
	"ANF": "Consumer Discretionary",
	"OTTR": "Utilities",
	"FG": "Financials",
	"VRNS": "Information Technology",
	"NHI": "Real Estate",
	"LEU": "Industrials",
	"OSIS": "Information Technology",
	"BMI": "Industrials",
	"KFY": "Consumer Discretionary",
	"ABG": "Consumer Discretionary",
	"CALM": "Consumer Staples",
	"AAP": "Consumer Discretionary",
	"VECO": "Information Technology",
	"BHF": "Financials",
	"CVBF": "Financials",
	"EWTX": "Health Care",
	"BFH": "Consumer Discretionary",
	"ASO": "Consumer Discretionary",
	"TXG": "Industrials",
	"BTU": "Energy",
	"CNS": "Financials",
	"QLYS": "Information Technology",
	"YETI": "Consumer Discretionary",
	"APLE": "Real Estate",
	"BELFB": "Other",
	"SMG": "Industrials",
	"BOX": "Information Technology",
	"RNG": "Information Technology",
	"OGN": "Health Care",
	"ORKA": "Health Care",
	"HGTY": "Financials",
	"FIZZ": "Consumer Staples",
	"FOUR": "Consumer Discretionary",
	"GPGI": "Financials",
	"BILL": "Information Technology",
	"ICUI": "Health Care",
	"COLM": "Consumer Discretionary",
	"FUL": "Industrials",
	"NAN": "Financials",
	"FIBK": "Financials",
	"BATRA": "Consumer Discretionary",
	"AB": "Financials",
	"DAVE": "Financials",
	"EXTR": "Communication Services",
	"SKYW": "Consumer Discretionary",
	"CC": "Industrials",
	"ELF": "Consumer Discretionary",
	"AVA": "Utilities",
	"GBDC": "Financials",
	"GPK": "Consumer Discretionary",
	"MHO": "Consumer Discretionary",
	"OPCH": "Health Care",
	"BKU": "Financials",
	"CVI": "Energy",
	"CBU": "Financials",
	"BEAM": "Health Care",
	"BULL": "Financials",
	"LIF": "Information Technology",
	"NSA": "Real Estate",
	"IAC": "Information Technology",
	"HWKN": "Consumer Discretionary",
	"NATL": "Other",
	"SXI": "Industrials",
	"WSBC": "Financials",
	"PTRN": "Consumer Discretionary",
	"DNLI": "Health Care",
	"AVNT": "Industrials",
	"MMS": "Consumer Discretionary",
	"GNW": "Financials",
	"FHB": "Financials",
	"MSGE": "Consumer Discretionary",
	"ALHC": "Health Care",
	"CSQ": "Financials",
	"ARLP": "Energy",
	"KN": "Consumer Staples",
	"CON": "Health Care",
	"INOD": "Information Technology",
	"BFAM": "Consumer Discretionary",
	"FFBC": "Financials",
	"MMED": "Health Care",
	"SLG": "Real Estate",
	"MCHB": "Financials",
	"BATRK": "Consumer Discretionary",
	"AEHR": "Industrials",
	"CAKE": "Consumer Discretionary",
	"USLM": "Industrials",
	"UNFI": "Consumer Discretionary",
	"CNK": "Consumer Discretionary",
	"VC": "Consumer Discretionary",
	"CHEF": "Consumer Discretionary",
	"GRAL": "Health Care",
	"SHOO": "Consumer Discretionary",
	"ATRO": "Industrials",
	"WRBY": "Health Care",
	"WOLF": "Information Technology",
	"MZTI": "Consumer Staples",
	"UPST": "Financials",
	"BELFA": "Other",
	"CRVL": "Financials",
	"NSIT": "Consumer Discretionary",
	"SFNC": "Financials",
	"BKD": "Health Care",
	"PRK": "Financials",
	"CTRI": "Utilities",
	"CLMT": "Energy",
	"GEO": "Consumer Discretionary",
	"LXP": "Real Estate",
	"IPAR": "Consumer Discretionary",
	"BXMT": "Real Estate",
	"KBH": "Consumer Discretionary",
	"RCUS": "Health Care",
	"CURB": "Financials",
	"GPOR": "Energy",
	"MPT": "Real Estate",
	"DYN": "Health Care",
	"VOYG": "Industrials",
	"PATK": "Consumer Discretionary",
	"BOH": "Financials",
	"HAYW": "Industrials",
	"ITGR": "Health Care",
	"EOSE": "Other",
	"OLN": "Industrials",
	"HAE": "Health Care",
	"NN": "Industrials",
	"BHE": "Information Technology",
	"HYMC": "Materials",
	"LFST": "Health Care",
	"FSK": "Financials",
	"APAM": "Financials",
	"KALU": "Industrials",
	"AEO": "Consumer Discretionary",
	"ADEA": "Information Technology",
	"AKR": "Real Estate",
	"AWR": "Utilities",
	"CWK": "Financials",
	"CECO": "Industrials",
	"NIC": "Financials",
	"ARCB": "Industrials",
	"TDC": "Information Technology",
	"KLRA": "Health Care",
	"NTCT": "Information Technology",
	"CPK": "Utilities",
	"AMPX": "Other",
	"GEF": "Other",
	"SBCF": "Financials",
	"VAC": "Financials",
	"PAY": "Consumer Discretionary",
	"GRBK": "Consumer Discretionary",
	"BKV": "Energy",
	"BANC": "Financials",
	"PLMR": "Financials",
	"RHI": "Consumer Discretionary",
	"TNGX": "Health Care",
	"PFS": "Financials",
	"NHC": "Health Care",
	"HTGC": "Financials",
	"HIW": "Real Estate",
	"PHIN": "Consumer Discretionary",
	"DBRG": "Real Estate",
	"TENB": "Information Technology",
	"WHR": "Consumer Discretionary",
	"BW": "Industrials",
	"UE": "Financials",
	"TR": "Consumer Staples",
	"BRZE": "Information Technology",
	"EXPO": "Consumer Discretionary",
	"PARR": "Energy",
	"BWIN": "Financials",
	"CALY": "Consumer Discretionary",
	"BSM": "Energy",
	"QTWO": "Information Technology",
	"RH": "Consumer Discretionary",
	"WT": "Financials",
	"DBD": "Other",
	"DX": "Real Estate",
	"VISN": "Information Technology",
	"MGEE": "Energy",
	"UNIT": "Real Estate",
	"WOR": "Industrials",
	"ATKR": "Other",
	"QUBT": "Information Technology",
	"NMIH": "Financials",
	"FCPT": "Real Estate",
	"HLIO": "Industrials",
	"PENG": "Information Technology",
	"LCII": "Consumer Discretionary",
	"CARG": "Information Technology",
	"HTFL": "Health Care",
	"MGRC": "Consumer Discretionary",
	"FBK": "Financials",
	"ALMS": "Health Care",
	"FA": "Information Technology",
	"PRVA": "Health Care",
	"DK": "Energy",
	"SUPN": "Health Care",
	"AMR": "Energy",
	"WDFC": "Industrials",
	"HUN": "Industrials",
	"IRON": "Health Care",
	"DKL": "Energy",
	"CCC": "Information Technology",
	"EEFT": "Financials",
	"OUST": "Industrials",
	"ARQT": "Health Care",
	"RLAY": "Health Care",
	"BRUN": "Information Technology",
	"SHAK": "Consumer Discretionary",
	"KD": "Information Technology",
	"FSLY": "Information Technology",
	"SAH": "Consumer Discretionary",
	"GDV": "Financials",
	"WAFD": "Financials",
	"ASH": "Consumer Discretionary",
	"CWT": "Utilities",
	"PTON": "Consumer Discretionary",
	"WK": "Information Technology",
	"FRPT": "Consumer Staples",
	"HUBG": "Industrials",
	"MLYS": "Health Care",
	"PENN": "Consumer Discretionary",
	"BKE": "Consumer Discretionary",
	"IVT": "Real Estate",
	"ROG": "Industrials",
	"TRMK": "Financials",
	"IDYA": "Health Care",
	"VERA": "Health Care",
	"DGII": "Communication Services",
	"KMT": "Industrials",
	"TARS": "Health Care",
	"DFTX": "Health Care",
	"TRN": "Industrials",
	"UAA": "Consumer Discretionary",
	"CALX": "Consumer Discretionary",
	"FRME": "Financials",
	"IMNM": "Health Care",
	"KWR": "Industrials",
	"COHU": "Industrials",
	"CUBI": "Financials",
	"HOG": "Consumer Discretionary",
	"TOWN": "Financials",
	"WU": "Consumer Discretionary",
	"NMRK": "Financials",
	"VVX": "Consumer Discretionary",
	"LCID": "Industrials",
	"WTTR": "Energy",
	"WERN": "Industrials",
	"CLDX": "Health Care",
	"FRSH": "Information Technology",
	"ELVN": "Health Care",
	"BCC": "Consumer Discretionary",
	"DJT": "Information Technology",
	"NIQ": "Information Technology",
	"TALO": "Energy",
	"CENT": "Consumer Discretionary",
	"GRDN": "Consumer Staples",
	"PK": "Consumer Discretionary",
	"NESR": "Energy",
	"ICHR": "Information Technology",
	"AMSC": "Consumer Discretionary",
	"BBT": "Financials",
	"ANDE": "Industrials",
	"ADPT": "Health Care",
	"FBNC": "Financials",
	"DNOW": "Consumer Discretionary",
	"MTX": "Materials",
	"NBTB": "Financials",
	"HTO": "Utilities",
	"NOVTU": "Other",
	"NGVT": "Industrials",
	"BBAI": "Information Technology",
	"TMDX": "Health Care",
	"DRVN": "Consumer Discretionary",
	"PLUS": "Information Technology",
	"ABM": "Consumer Discretionary",
	"HE": "Utilities",
	"PCT": "Industrials",
	"AGYS": "Information Technology",
	"BCRX": "Health Care",
	"DXPE": "Industrials",
	"CXT": "Industrials",
	"BUSE": "Financials",
	"NOG": "Energy",
	"DCO": "Industrials",
	"PBH": "Health Care",
	"TBBK": "Financials",
	"RARE": "Health Care",
	"HNI": "Consumer Discretionary",
	"DRH": "Real Estate",
	"CDNL": "Industrials",
	"SOC": "Energy",
	"KOD": "Health Care",
	"RAMP": "Information Technology",
	"MNR": "Energy",
	"BANR": "Financials",
	"BLBD": "Consumer Discretionary",
	"EFSC": "Financials",
	"HTH": "Financials",
	"CLOV": "Health Care",
	"THR": "Energy",
	"NKTR": "Health Care",
	"FLOC": "Consumer Discretionary",
	"ACHC": "Health Care",
	"CENTA": "Consumer Discretionary",
	"ALRM": "Information Technology",
	"AVPT": "Information Technology",
	"MBIN": "Financials",
	"GCMG": "Financials",
	"LMAT": "Health Care",
	"BTX": "Other",
	"CXW": "Real Estate",
	"AXGN": "Health Care",
	"UTI": "Real Estate",
	"MCRI": "Consumer Discretionary",
	"WS": "Industrials",
	"PBI": "Other",
	"WLY": "Consumer Discretionary",
	"WLYB": "Consumer Discretionary",
	"ASTH": "Consumer Discretionary",
	"NEXT": "Utilities",
	"AESI": "Industrials",
	"ARR": "Real Estate",
	"BGR": "Financials",
	"ATEN": "Communication Services",
	"SYBT": "Financials",
	"SLDE": "Financials",
	"TNET": "Consumer Discretionary",
	"CLBK": "Financials",
	"DHC": "Real Estate",
	"PRDO": "Real Estate",
	"FUN": "Consumer Discretionary",
	"NWN": "Utilities",
	"MGNI": "Information Technology",
	"BRSL": "Consumer Discretionary",
	"XRAY": "Health Care",
	"NWBI": "Financials",
	"TRVI": "Health Care",
	"FIGS": "Consumer Discretionary",
	"SEM": "Health Care",
	"SHLS": "Information Technology",
	"VERX": "Information Technology",
	"OMCL": "Information Technology",
	"SHO": "Consumer Discretionary",
	"IOSP": "Industrials",
	"NEOG": "Health Care",
	"NGL": "Utilities",
	"PGNY": "Health Care",
	"STC": "Financials",
	"GNL": "Real Estate",
	"RVT": "Financials",
	"PLAB": "Information Technology",
	"OCUL": "Health Care",
	"JBLU": "Consumer Discretionary",
	"GTY": "Financials",
	"EZPW": "Consumer Discretionary",
	"GRC": "Industrials",
	"HCI": "Financials",
	"STOK": "Health Care",
	"NTST": "Real Estate",
	"SPSC": "Information Technology",
	"LC": "Financials",
	"COTY": "Consumer Discretionary",
	"EVCM": "Information Technology",
	"PDFS": "Information Technology",
	"AGM": "Financials",
	"TYRA": "Health Care",
	"AMRC": "Consumer Discretionary",
	"LTC": "Real Estate",
	"DEI": "Real Estate",
	"SION": "Health Care",
	"FLYW": "Consumer Discretionary",
	"FCF": "Financials",
	"IOVA": "Health Care",
	"SKYT": "Information Technology",
	"BKSY": "Information Technology",
	"NBHC": "Financials",
	"TY": "Financials",
	"NTLA": "Health Care",
	"STEL": "Financials",
	"RAPP": "Health Care",
	"SONO": "Consumer Staples",
	"KYN": "Financials",
	"ALKT": "Information Technology",
	"GEL": "Energy",
	"SAM": "Consumer Staples",
	"PDO": "Financials",
	"HMN": "Financials",
	"PRKS": "Health Care",
	"ADNT": "Consumer Discretionary",
	"ZYME": "Health Care",
	"PUMP": "Energy",
	"ALG": "Industrials",
	"INVX": "Consumer Discretionary",
	"CTS": "Information Technology",
	"TIC": "Consumer Discretionary",
	"BAND": "Information Technology",
	"HLIT": "Information Technology",
	"PLPC": "Industrials",
	"WMK": "Consumer Staples",
	"ADMA": "Health Care",
	"AIN": "Consumer Discretionary",
	"NRIX": "Health Care",
	"SRPT": "Health Care",
	"HRMY": "Health Care",
	"RXRX": "Health Care",
	"ANIP": "Health Care",
	"SPB": "Other",
	"MUJ": "Financials",
	"SKWD": "Financials",
	"AGIO": "Health Care",
	"FBYD": "Consumer Discretionary",
	"VRDN": "Health Care",
	"RQI": "Financials",
	"MIY": "Financials",
	"SGRY": "Health Care",
	"WLTH": "Financials",
	"LPG": "Consumer Discretionary",
	"GT": "Consumer Discretionary",
	"PRLB": "Industrials",
	"MD": "Health Care",
	"AMBQ": "Information Technology",
	"SRCE": "Financials",
	"LWLG": "Industrials",
	"UFPT": "Health Care",
	"PEB": "Real Estate",
	"CHCO": "Financials",
	"NVRI": "Other",
	"KSS": "Consumer Discretionary",
	"SNDX": "Health Care",
	"VCEL": "Health Care",
	"FIVN": "Information Technology",
	"STRA": "Real Estate",
	"ADUS": "Health Care",
	"SMA": "Real Estate",
	"WD": "Financials",
	"EPAC": "Information Technology",
	"LOB": "Financials",
	"CASH": "Financials",
	"RCAT": "Information Technology",
	"TILE": "Consumer Discretionary",
	"CBZ": "Consumer Discretionary",
	"HURN": "Consumer Discretionary",
	"HTZ": "Consumer Discretionary",
	"OXLC": "Financials",
	"MHD": "Financials",
	"TH": "Consumer Discretionary",
	"NCNO": "Information Technology",
	"GLOB": "Information Technology",
	"ECPG": "Financials",
	"CNXN": "Consumer Discretionary",
	"PLSE": "Health Care",
	"TPB": "Consumer Discretionary",
	"BCAT": "Financials",
	"SNDA": "Health Care",
	"SLS": "Health Care",
	"PAYO": "Consumer Discretionary",
	"AIP": "Information Technology",
	"EFC": "Financials",
	"TSHA": "Health Care",
	"MQY": "Financials",
	"NVAX": "Health Care",
	"FMC": "Industrials",
	"IMKTA": "Consumer Staples",
	"VSTS": "Consumer Discretionary",
	"CAPR": "Health Care",
	"ECAT": "Financials",
	"TFIN": "Financials",
	"XPRO": "Energy",
	"GENB": "Health Care",
	"ALGT": "Consumer Discretionary",
	"MQ": "Information Technology",
	"SILA": "Real Estate",
	"IIPR": "Financials",
	"ENVX": "Other",
	"VPG": "Information Technology",
	"FRA": "Financials",
	"PVLA": "Health Care",
	"ZD": "Communication Services",
	"ANAB": "Health Care",
	"FSUN": "Financials",
	"GAB": "Financials",
	"NUVB": "Health Care",
	"DCOM": "Financials",
	"GLUE": "Health Care",
	"LILAK": "Communication Services",
	"BDJ": "Financials",
	"GLP": "Energy",
	"FLO": "Consumer Staples",
	"GABC": "Financials",
	"PWP": "Financials",
	"AEVA": "Consumer Discretionary",
	"MYI": "Financials",
	"WBTN": "Consumer Discretionary",
	"XHR": "Consumer Discretionary",
	"APPN": "Information Technology",
	"ETV": "Financials",
	"STBA": "Financials",
	"INVA": "Health Care",
	"CNXC": "Information Technology",
	"VIR": "Health Care",
	"PGEN": "Health Care",
	"LILA": "Communication Services",
	"DCH": "Consumer Discretionary",
	"ASAN": "Information Technology",
	"TCBK": "Financials",
	"MUC": "Financials",
	"HOPE": "Financials",
	"AVAH": "Health Care",
	"MUA": "Financials",
	"BL": "Information Technology",
	"REX": "Industrials",
	"INTA": "Information Technology",
	"PRGO": "Health Care",
	"FRMEP": "Financials",
	"AMLX": "Health Care",
	"NCV": "Financials",
	"RBCAA": "Financials",
	"KRP": "Energy",
	"BFC": "Financials",
	"SLVM": "Materials",
	"BKT": "Financials",
	"LZB": "Consumer Discretionary",
	"PRCT": "Health Care",
	"ARDX": "Health Care",
	"BHVN": "Health Care",
	"CCS": "Consumer Discretionary",
	"KW": "Financials",
	"GAM": "Financials",
	"INBX": "Health Care",
	"RLJ": "Real Estate",
	"MBX": "Health Care",
	"NWL": "Industrials",
	"DXC": "Information Technology",
	"TRIN": "Financials",
	"LINC": "Real Estate",
	"QCRH": "Financials",
	"AGL": "Health Care",
	"LIND": "Consumer Discretionary",
	"CNOB": "Financials",
	"BY": "Financials",
	"LKFN": "Financials",
	"KMPR": "Financials",
	"CBL": "Real Estate",
	"NNE": "Utilities",
	"PRG": "Consumer Discretionary",
	"TNC": "Industrials",
	"WGS": "Information Technology",
	"RES": "Energy",
	"AI": "Information Technology",
	"TRS": "Industrials",
	"DV": "Information Technology",
	"GBX": "Industrials",
	"CRI": "Consumer Discretionary",
	"HLMN": "Consumer Discretionary",
	"RYZ": "Industrials",
	"OBK": "Financials",
	"ECVT": "Industrials",
	"RVLV": "Consumer Discretionary",
	"WKC": "Energy",
	"MAZE": "Health Care",
	"ARI": "Real Estate",
	"WWW": "Consumer Discretionary",
	"CSWC": "Consumer Discretionary",
	"JJSF": "Consumer Staples",
	"STAA": "Health Care",
	"ARLO": "Consumer Staples",
	"BKKT": "Financials",
	"AAT": "Real Estate",
	"MRTN": "Industrials",
	"BCAX": "Health Care",
	"WEN": "Consumer Discretionary",
	"ARRY": "Consumer Discretionary",
	"HCSG": "Health Care",
	"ATRC": "Health Care",
	"DFH": "Consumer Discretionary",
	"FTRE": "Health Care",
	"LEG": "Consumer Discretionary",
	"UMAC": "Information Technology",
	"TTI": "Energy",
	"MAN": "Consumer Discretionary",
	"AHCO": "Health Care",
	"WLFC": "Consumer Discretionary",
	"WINA": "Consumer Discretionary",
	"SEPN": "Health Care",
	"FOR": "Financials",
	"NRP": "Energy",
	"OI": "Consumer Discretionary",
	"BLKB": "Information Technology",
	"WLDN": "Consumer Discretionary",
	"GCT": "Consumer Discretionary",
	"EYE": "Health Care",
	"GIII": "Consumer Discretionary",
	"ORC": "Real Estate",
	"SVV": "Consumer Discretionary",
	"PBT": "Energy",
	"OLPX": "Consumer Discretionary",
	"HLX": "Energy",
	"MLTX": "Health Care",
	"ADTN": "Utilities",
	"ALMR": "Industrials",
	"CDRE": "Health Care",
	"CMP": "Industrials",
	"ARDT": "Health Care",
	"TDOC": "Health Care",
	"IDT": "Communication Services",
	"MPLT": "Health Care",
	"UAMY": "Industrials",
	"IPX": "Materials",
	"UMH": "Real Estate",
	"ULCC": "Consumer Discretionary",
	"NEO": "Health Care",
	"ENOV": "Health Care",
	"TROX": "Industrials",
	"PRCH": "Information Technology",
	"HROW": "Health Care",
	"YSWY": "Consumer Staples",
	"NSSC": "Communication Services",
	"COAG": "Health Care",
	"KDK": "Information Technology",
	"LADR": "Real Estate",
	"ASST": "Information Technology",
	"TWO": "Real Estate",
	"WABC": "Financials",
	"NSP": "Consumer Discretionary",
	"SPH": "Consumer Discretionary",
	"UAN": "Industrials",
	"DMLP": "Energy",
	"XPEL": "Industrials",
	"FCEL": "Energy",
	"PAHC": "Health Care",
	"PRGS": "Information Technology",
	"HYLN": "Consumer Discretionary",
	"BHRB": "Financials",
	"YELP": "Consumer Discretionary",
	"ATLC": "Financials",
	"IART": "Health Care",
	"CRSR": "Information Technology",
	"ALX": "Real Estate",
	"UVV": "Industrials",
	"NPKI": "Consumer Discretionary",
	"ENR": "Other",
	"TRIP": "Information Technology",
	"ALNT": "Industrials",
	"DSGR": "Consumer Discretionary",
	"SBH": "Consumer Discretionary",
	"AVBP": "Health Care",
	"GSHD": "Financials",
	"CXM": "Information Technology",
	"ICFI": "Consumer Discretionary",
	"SHAZ": "Information Technology",
	"PEBO": "Financials",
	"TMP": "Financials",
	"AMAL": "Financials",
	"WYFI": "Financials",
	"VTOL": "Consumer Discretionary",
	"PRSU": "Consumer Discretionary",
	"GOLD": "Industrials",
	"INSP": "Health Care",
	"KMTS": "Health Care",
	"BLFS": "Health Care",
	"PURR": "Financials",
	"LIFE": "Financials",
	"PRA": "Financials",
	"SCL": "Consumer Discretionary",
	"CCO": "Consumer Discretionary",
	"LUCK": "Consumer Discretionary",
	"ATEX": "Communication Services",
	"ATEC": "Health Care",
	"SG": "Consumer Discretionary",
	"EVEX": "Industrials",
	"INDI": "Information Technology",
	"CTBI": "Financials",
	"NCZ": "Financials",
	"RXT": "Information Technology",
	"BFLY": "Health Care",
	"RMIX": "Industrials",
	"SBET": "Information Technology",
	"MRVI": "Health Care",
	"BV": "Consumer Discretionary",
	"PNTG": "Health Care",
	"RR": "Industrials",
	"PSEC": "Financials",
	"AVLN": "Health Care",
	"PGY": "Financials",
	"REAL": "Consumer Discretionary",
	"VIA": "Information Technology",
	"IRMD": "Health Care",
	"CDNA": "Health Care",
	"ZBIO": "Health Care",
	"EVLV": "Information Technology",
	"GHM": "Industrials",
	"FMBH": "Financials",
	"HTLD": "Industrials",
	"SVC": "Real Estate",
	"ROCK": "Industrials",
	"CEVA": "Information Technology",
	"GIC": "Industrials",
	"MBC": "Consumer Discretionary",
	"ASTE": "Industrials",
	"AVNS": "Health Care",
	"NWPX": "Industrials",
	"ASA": "Industrials",
	"PSNL": "Health Care",
	"UFCS": "Financials",
	"ODC": "Consumer Discretionary",
	"TNDM": "Health Care",
	"LNN": "Industrials",
	"PZZA": "Consumer Discretionary",
	"LPTH": "Information Technology",
	"DEC": "Other",
	"CSR": "Real Estate",
	"CIM": "Real Estate",
	"LQDT": "Consumer Discretionary",
	"LGIH": "Consumer Discretionary",
	"TDAY": "Consumer Discretionary",
	"UPBD": "Consumer Discretionary",
	"EYPT": "Industrials",
	"FUBO": "Consumer Discretionary",
	"AKTS": "Health Care",
	"NMAX": "Industrials",
	"DEA": "Real Estate",
	"HFWA": "Financials",
	"MLKN": "Consumer Discretionary",
	"DSL": "Financials",
	"MNKD": "Health Care",
	"PCTTU": "Industrials",
	"XIFR": "Utilities",
	"ABTC": "Information Technology",
	"MCB": "Financials",
	"OLMA": "Health Care",
	"DLX": "Consumer Discretionary",
	"GPRE": "Industrials",
	"KOPN": "Information Technology",
	"SBR": "Energy",
	"BTZ": "Financials",
	"ACVA": "Consumer Discretionary",
	"JBGS": "Real Estate",
	"ACDC": "Energy",
	"RJET": "Consumer Discretionary",
	"UVSP": "Financials",
	"AORT": "Health Care",
	"OSBC": "Financials",
	"BST": "Financials",
	"XERS": "Health Care",
	"METC": "Energy",
	"ABR": "Real Estate",
	"SAFE": "Real Estate",
	"AMN": "Consumer Discretionary",
	"OCFC": "Financials",
	"COLL": "Health Care",
	"OPK": "Health Care",
	"LZ": "Information Technology",
	"UTZ": "Consumer Staples",
	"GENVR": "Information Technology",
	"CCB": "Financials",
	"MMI": "Financials",
	"NHP": "Other",
	"CNMD": "Health Care",
	"THRM": "Consumer Discretionary",
	"SMPL": "Consumer Staples",
	"UPWK": "Information Technology",
	"PDM": "Real Estate",
	"OMDA": "Health Care",
	"SDGR": "Health Care",
	"AEF": "Financials",
	"CRVS": "Health Care",
	"GNK": "Consumer Discretionary",
	"UVE": "Financials",
	"ETW": "Financials",
	"SVRA": "Health Care",
	"OCSL": "Financials",
	"HBT": "Financials",
	"AZTA": "Information Technology",
	"SAFT": "Financials",
	"SBGI": "Industrials",
	"PLOW": "Industrials",
	"JBIO": "Health Care",
	"BCX": "Financials",
	"INNV": "Health Care",
	"TWFG": "Financials",
	"APPS": "Other",
	"NBN": "Financials",
	"BRBR": "Consumer Staples",
	"GDRX": "Information Technology",
	"FSCO": "Financials",
	"GSBD": "Financials",
	"DAKT": "Consumer Discretionary",
	"DFIN": "Consumer Discretionary",
	"CVLG": "Industrials",
	"CCOI": "Consumer Discretionary",
	"EEX": "Consumer Discretionary",
	"CFFN": "Financials",
	"ESRT": "Real Estate",
	"SENEB": "Consumer Staples",
	"SENEA": "Consumer Staples",
	"SBSI": "Financials",
	"KODK": "Consumer Discretionary",
	"LXRX": "Health Care",
	"ACEL": "Consumer Discretionary",
	"ASPI": "Industrials",
	"BJRI": "Consumer Discretionary",
	"WSR": "Real Estate",
	"OPY": "Financials",
	"MFA": "Real Estate",
	"WOOF": "Consumer Discretionary",
	"USPH": "Health Care",
	"MSEX": "Utilities",
	"ARHS": "Consumer Discretionary",
	"FMN": "Financials",
	"SPIR": "Consumer Discretionary",
	"PSIX": "Industrials",
	"AMC": "Consumer Discretionary",
	"TRUP": "Health Care",
	"CRAI": "Consumer Discretionary",
	"EQBK": "Financials",
	"TRON": "Consumer Discretionary",
	"RHLD": "Financials",
	"SPTX": "Health Care",
	"JCAP": "Financials",
	"VRTS": "Financials",
	"LMB": "Consumer Discretionary",
	"HBNC": "Financials",
	"ABSI": "Health Care",
	"ESQ": "Financials",
	"GTM": "Information Technology",
	"NPK": "Industrials",
	"CGEM": "Health Care",
	"MCBS": "Financials",
	"APEI": "Real Estate",
	"VYX": "Other",
	"SPRY": "Health Care",
	"HNRG": "Energy",
	"PCRX": "Health Care",
	"LXU": "Materials",
	"SCSC": "Information Technology",
	"HQH": "Financials",
	"GLIBA": "Communication Services",
	"GLIBK": "Communication Services",
	"MGTX": "Health Care",
	"BFST": "Financials",
	"HMH": "Consumer Discretionary",
	"UTL": "Utilities",
	"PMT": "Real Estate",
	"RPC": "Financials",
	"NRGV": "Other",
	"MBWM": "Financials",
	"CCNE": "Financials",
	"AMPL": "Information Technology",
	"BBDC": "Financials",
	"CPF": "Financials",
	"SMP": "Consumer Discretionary",
	"FSBC": "Financials",
	"COUR": "Information Technology",
	"JANX": "Health Care",
	"NUTX": "Consumer Discretionary",
	"HAFC": "Financials",
	"TRST": "Financials",
	"AIAI": "Information Technology",
	"LYTS": "Consumer Discretionary",
	"MFIC": "Financials",
	"NBBK": "Financials",
	"QDEL": "Health Care",
	"SHEN": "Communication Services",
	"SCHL": "Consumer Discretionary",
	"XNCR": "Health Care",
	"JBSS": "Consumer Staples",
	"ABX": "Financials",
	"KURA": "Health Care",
	"HPK": "Energy",
	"AMTB": "Financials",
	"CERT": "Information Technology",
	"BOW": "Financials",
	"ANNX": "Health Care",
	"ARKO": "Consumer Staples",
	"INR": "Energy",
	"ORIC": "Health Care",
	"MYE": "Industrials",
	"ETON": "Health Care",
	"SANA": "Health Care",
	"TALK": "Health Care",
	"NB": "Materials",
	"CRCT": "Information Technology",
	"NX": "Industrials",
	"IMSR": "Other",
	"BCSF": "Financials",
	"SSYS": "Information Technology",
	"EVC": "Industrials",
	"KRO": "Materials",
	"EFOR": "Consumer Discretionary",
	"CODI": "Consumer Discretionary",
	"WGO": "Industrials",
	"AVR": "Health Care",
	"GO": "Consumer Staples",
	"AMPH": "Health Care",
	"BFS": "Real Estate",
	"AVTX": "Health Care",
	"MATW": "Communication Services",
	"FMNB": "Financials",
	"CAPL": "Energy",
	"CAC": "Financials",
	"EVMN": "Health Care",
	"MPB": "Financials",
	"ROOT": "Financials",
	"NXDR": "Information Technology",
	"EGBN": "Financials",
	"ADAM": "Real Estate",
	"MTUS": "Industrials",
	"PHAT": "Health Care",
	"THFF": "Financials",
	"PFLT": "Financials",
	"MRLN": "Information Technology",
	"VOR": "Health Care",
	"HCMA": "Consumer Discretionary",
	"FCBC": "Financials",
	"CTMX": "Health Care",
	"OMER": "Health Care",
	"ODTX": "Health Care",
	"APOG": "Consumer Discretionary",
	"ESPR": "Health Care",
	"GRPN": "Consumer Discretionary",
	"IBTA": "Consumer Discretionary",
	"EPC": "Consumer Discretionary",
	"WLKP": "Industrials",
	"GERN": "Health Care",
	"AGNT": "Financials",
	"WRLD": "Financials",
	"KFRC": "Consumer Discretionary",
	"AVO": "Consumer Staples",
	"KOP": "Materials",
	"MOV": "Consumer Discretionary",
	"FOXF": "Consumer Discretionary",
	"LBRX": "Health Care",
	"EIG": "Financials",
	"HTB": "Financials",
	"CWH": "Consumer Discretionary",
	"BBSI": "Consumer Discretionary",
	"CCBG": "Financials",
	"SXC": "Industrials",
	"WEST": "Consumer Staples",
	"NAVI": "Financials",
	"GSBC": "Financials",
	"ALLO": "Health Care",
	"AURA": "Health Care",
	"HZO": "Consumer Discretionary",
	"SPFI": "Financials",
	"RDVT": "Information Technology",
	"CYRX": "Health Care",
	"PGC": "Financials",
	"VELO": "Information Technology",
	"REPX": "Energy",
	"CGBD": "Financials",
	"CBRL": "Consumer Discretionary",
	"SLDP": "Other",
	"SMBC": "Financials",
	"MITK": "Information Technology",
	"RLMD": "Health Care",
	"DSP": "Information Technology",
	"BIOA": "Health Care",
	"NMFC": "Financials",
	"NXRT": "Real Estate",
	"DC": "Materials",
	"BRSP": "Real Estate",
	"FPH": "Financials",
	"METCB": "Energy",
	"NIE": "Financials",
	"FEIM": "Industrials",
	"BVS": "Health Care",
	"FTK": "Industrials",
	"LMRI": "Health Care",
	"TRNS": "Industrials",
	"JBI": "Industrials",
	"SERV": "Consumer Discretionary",
	"GDOT": "Financials",
	"IHRT": "Consumer Discretionary",
	"MRAM": "Information Technology",
	"IVR": "Real Estate",
	"ORRF": "Financials",
	"KELYB": "Consumer Discretionary",
	"ALRS": "Financials",
	"PKE": "Industrials",
	"VTS": "Energy",
	"TBLD": "Financials",
	"FWRG": "Consumer Discretionary",
	"FDUS": "Financials",
	"HSTM": "Information Technology",
	"SLRC": "Financials",
	"TXO": "Energy",
	"DJCO": "Consumer Discretionary",
	"ELA": "Consumer Discretionary",
	"QNST": "Consumer Discretionary",
	"SMBK": "Financials",
	"BLMN": "Consumer Discretionary",
	"OPFI": "Financials",
	"ANRO": "Health Care",
	"DGICB": "Financials",
	"BTBT": "Financials",
	"CBLL": "Health Care",
	"BBOT": "Health Care",
	"FISI": "Financials",
	"CTO": "Real Estate",
	"IBCP": "Financials",
	"AMWD": "Materials",
	"OXM": "Industrials",
	"SKYH": "Financials",
	"MNTN": "Consumer Discretionary",
	"SLDB": "Health Care",
	"VLGEA": "Consumer Staples",
	"KRUS": "Consumer Discretionary",
	"VEL": "Financials",
	"SHBI": "Financials",
	"NTGR": "Utilities",
	"BZH": "Consumer Discretionary",
	"BALY": "Consumer Discretionary",
	"NGVC": "Consumer Staples",
	"FOF": "Financials",
	"EVGO": "Information Technology",
	"SWBI": "Industrials",
	"DLY": "Financials",
	"CSV": "Consumer Discretionary",
	"ZVRA": "Health Care",
	"BSTZ": "Financials",
	"HIPO": "Financials",
	"RWT": "Real Estate",
	"DSGN": "Health Care",
	"CSTL": "Health Care",
	"EVER": "Information Technology",
	"HRTG": "Financials",
	"NXP": "Financials",
	"RSVR": "Consumer Discretionary",
	"FBRT": "Real Estate",
	"SGP": "Health Care",
	"HOV": "Consumer Discretionary",
	"CRMD": "Health Care",
	"SABR": "Information Technology",
	"VMO": "Financials",
	"TLRY": "Health Care",
	"TIPT": "Financials",
	"HPP": "Financials",
	"XFLT": "Financials",
	"CWBC": "Financials",
	"CNNE": "Consumer Discretionary",
	"TRTX": "Real Estate",
	"GRNT": "Energy",
	"HY": "Industrials",
	"NABL": "Information Technology",
	"CLYM": "Health Care",
	"PSTL": "Real Estate",
	"RMT": "Financials",
	"GOGO": "Consumer Discretionary",
	"BH": "Consumer Discretionary",
	"NCDL": "Other",
	"SIBN": "Health Care",
	"ACRS": "Health Care",
	"SWIM": "Industrials",
	"KE": "Information Technology",
	"SWMR": "Information Technology",
	"TCBX": "Financials",
	"CTRN": "Consumer Discretionary",
	"CLFD": "Utilities",
	"RMR": "Consumer Discretionary",
	"PAR": "Other",
	"DGICA": "Financials",
	"PD": "Information Technology",
	"INN": "Real Estate",
	"GAIN": "Financials",
	"RGR": "Industrials",
	"VRRM": "Consumer Discretionary",
	"SDHC": "Consumer Discretionary",
	"RYAM": "Materials",
	"ASIX": "Industrials",
	"GEMI": "Financials",
	"WASH": "Financials",
	"IMMX": "Health Care",
	"GDYN": "Information Technology",
	"GOOD": "Real Estate",
	"TDUP": "Consumer Discretionary",
	"CABA": "Health Care",
	"PRME": "Health Care",
	"CTGO": "Materials",
	"AROW": "Financials",
	"HIFS": "Financials",
	"IDR": "Materials",
	"BCAL": "Financials",
	"RRBI": "Consumer Discretionary",
	"AIV": "Real Estate",
	"PFIS": "Financials",
	"PACK": "Consumer Discretionary",
	"CARE": "Financials",
	"NPB": "Financials",
	"ALT": "Health Care",
	"SUJA": "Consumer Staples",
	"CASS": "Consumer Discretionary",
	"ALOY": "Information Technology",
	"NFBK": "Financials",
	"ILPT": "Real Estate",
	"NPCE": "Health Care",
	"CADL": "Health Care",
	"IRWD": "Health Care",
	"CBIO": "Health Care",
	"MAMA": "Consumer Staples",
	"DNUT": "Consumer Staples",
	"CCSI": "Information Technology",
	"DNA": "Health Care",
	"PRAA": "Financials",
	"CERS": "Information Technology",
	"PHR": "Consumer Discretionary",
	"BHB": "Financials",
	"MCS": "Consumer Discretionary",
	"UHT": "Real Estate",
	"ORN": "Industrials",
	"TASK": "Information Technology",
	"LEGH": "Consumer Discretionary",
	"TCMD": "Health Care",
	"MSBI": "Financials",
	"HUYA": "Information Technology",
	"BWMN": "Consumer Discretionary",
	"FET": "Consumer Discretionary",
	"AMSF": "Financials",
	"SSTK": "Information Technology",
	"ARVN": "Health Care",
	"MLAB": "Industrials",
	"CARS": "Information Technology",
	"ONT": "Consumer Discretionary",
	"UNTY": "Financials",
	"NRDS": "Information Technology",
	"TECX": "Health Care",
	"IIIV": "Information Technology",
	"MG": "Consumer Discretionary",
	"SRTA": "Consumer Discretionary",
	"SMC": "Utilities",
	"EIKN": "Health Care",
	"RFI": "Financials",
	"VGM": "Financials",
	"GYRE": "Health Care",
	"ACNB": "Financials",
	"MLR": "Consumer Discretionary",
	"RIGL": "Health Care",
	"EGY": "Energy",
	"MAX": "Consumer Discretionary",
	"WTI": "Energy",
	"TRAX": "Health Care",
	"NRIM": "Financials",
	"PROK": "Health Care",
	"MBUU": "Industrials",
	"MDXG": "Health Care",
	"SFST": "Financials",
	"KRT": "Industrials",
	"ACHV": "Health Care",
	"CPS": "Consumer Discretionary",
	"XMAX": "Consumer Discretionary",
	"RBBN": "Information Technology",
	"FFIC": "Financials",
	"VKQ": "Financials",
	"BBNX": "Health Care",
	"FIP": "Energy",
	"TREE": "Financials",
	"CRNC": "Information Technology",
	"IIIN": "Industrials",
	"CIVB": "Financials",
	"ETD": "Consumer Discretionary",
	"MEC": "Industrials",
	"BME": "Financials",
	"SD": "Energy",
	"MVST": "Other",
	"CTKB": "Industrials",
	"BDN": "Real Estate",
	"KRNY": "Financials",
	"PUBM": "Information Technology",
	"TYG": "Financials",
	"IPI": "Industrials",
	"BWB": "Financials",
	"TRC": "Financials",
	"ASPN": "Consumer Discretionary",
	"ANGX": "Consumer Discretionary",
	"KYTX": "Health Care",
	"XOMA": "Health Care",
	"PRTA": "Health Care",
	"CBNK": "Financials",
	"ADV": "Consumer Discretionary",
	"NGS": "Energy",
	"EBF": "Consumer Discretionary",
	"FLGT": "Health Care",
	"AHRT": "Financials",
	"OLP": "Real Estate",
	"ABAT": "Materials",
	"OSPN": "Information Technology",
	"CLDT": "Real Estate",
	"DDD": "Information Technology",
	"PRTH": "Consumer Discretionary",
	"ACIC": "Financials",
	"SES": "Other",
	"ALIT": "Consumer Discretionary",
	"HBCP": "Financials",
	"TITN": "Consumer Discretionary",
	"ETO": "Financials",
	"MATV": "Materials",
	"FTHY": "Financials",
	"ALTI": "Financials",
	"AQST": "Health Care",
	"SFIX": "Consumer Discretionary",
	"OIS": "Consumer Discretionary",
	"PANL": "Consumer Discretionary",
	"BSRR": "Financials",
	"MNRO": "Consumer Discretionary",
	"CTNM": "Health Care",
	"RPD": "Information Technology",
	"CAL": "Consumer Discretionary",
	"CHCT": "Real Estate",
	"INV": "Financials",
	"OVID": "Health Care",
	"STRO": "Health Care",
	"BBW": "Consumer Discretionary",
	"OOMA": "Information Technology",
	"NVEC": "Information Technology",
	"ANGO": "Health Care",
	"AIOT": "Communication Services",
	"XRN": "Real Estate",
	"SCVL": "Consumer Discretionary",
	"YORW": "Utilities",
	"FBIZ": "Financials",
	"PKOH": "Industrials",
	"OCGN": "Health Care",
	"JOUT": "Consumer Discretionary",
	"BBBY": "Consumer Discretionary",
	"EBS": "Health Care",
	"ELMT": "Industrials",
	"NUAI": "Energy",
	"TOI": "Health Care",
	"COFS": "Financials",
	"GETY": "Consumer Discretionary",
	"PLAY": "Consumer Discretionary",
	"FDMT": "Health Care",
	"TWI": "Industrials",
	"CVGW": "Consumer Discretionary",
	"CMCO": "Industrials",
	"GEVO": "Industrials",
	"CATX": "Health Care",
	"OBT": "Financials",
	"BLZE": "Information Technology",
	"WEAV": "Information Technology",
	"ZSQR": "Financials",
	"ETB": "Financials",
	"STTK": "Health Care",
	"KIDS": "Health Care",
	"GUT": "Financials",
	"PACB": "Industrials",
	"SPCE": "Consumer Discretionary",
	"CLNE": "Utilities",
	"PDLB": "Financials",
	"FULC": "Health Care",
	"FPI": "Real Estate",
	"ACTG": "Other",
	"HQL": "Financials",
	"UPB": "Health Care",
	"KLC": "Consumer Discretionary",
	"ITIC": "Financials",
	"IMXI": "Consumer Discretionary",
	"NPWR": "Energy",
	"SGMT": "Health Care",
	"FRPH": "Financials",
	"BLW": "Consumer Discretionary",
	"VITL": "Consumer Staples",
	"LAB": "Industrials",
	"ERII": "Information Technology",
	"OPTX": "Information Technology",
	"OSS": "Information Technology",
	"NRC": "Health Care",
	"VREX": "Information Technology",
	"LDI": "Financials",
	"ASMB": "Health Care",
	"GCBC": "Financials",
	"EVH": "Consumer Discretionary",
	"ATNI": "Communication Services",
	"GLAD": "Consumer Discretionary",
	"ZUMZ": "Consumer Discretionary",
	"GLOO": "Information Technology",
	"CMPX": "Health Care",
	"MTW": "Industrials",
	"EOLS": "Health Care",
	"ATOM": "Information Technology",
	"AMCX": "Communication Services",
	"MNPR": "Health Care",
	"KREF": "Real Estate",
	"IPSC": "Health Care",
	"MOBI": "Health Care",
	"ULH": "Industrials",
	"DUOT": "Information Technology",
	"GTN": "Industrials",
	"BRCC": "Consumer Staples",
	"BRCB": "Consumer Discretionary",
	"FBRX": "Health Care",
	"DVLT": "Information Technology",
	"BMBL": "Information Technology",
	"LOCO": "Consumer Discretionary",
	"GBFH": "Financials",
	"CCRN": "Consumer Discretionary",
	"BYND": "Consumer Staples",
	"ALMU": "Information Technology",
	"BSVN": "Financials",
	"FSTR": "Industrials",
	"CCAP": "Financials",
	"SPT": "Information Technology",
	"BWFG": "Financials",
	"SGU": "Consumer Discretionary",
	"SIDU": "Communication Services",
	"CTEV": "Consumer Discretionary",
	"MEI": "Information Technology",
	"BMRC": "Financials",
	"CBAN": "Financials",
	"BLND": "Information Technology",
	"PDYN": "Information Technology",
	"VHI": "Materials",
	"NATH": "Consumer Discretionary",
	"LAND": "Real Estate",
	"BXC": "Consumer Discretionary",
	"DDT": "Consumer Discretionary",
	"STRZ": "Consumer Discretionary",
	"HNST": "Consumer Discretionary",
	"WTBA": "Financials",
	"MAGN": "Materials",
	"LTBR": "Consumer Discretionary",
	"BOC": "Financials",
	"CCCC": "Health Care",
	"KELYA": "Consumer Discretionary",
	"ALTO": "Industrials",
	"RBB": "Financials",
	"YEXT": "Information Technology",
	"PAYS": "Information Technology",
	"FVR": "Real Estate",
	"GLSI": "Health Care",
	"NEWT": "Financials",
	"DBI": "Consumer Discretionary",
	"CBK": "Financials",
	"BBCP": "Consumer Discretionary",
	"VNDA": "Health Care",
	"LEO": "Financials",
	"LXEO": "Health Care",
	"MYGN": "Health Care",
	"XRX": "Information Technology",
	"BNTC": "Health Care",
	"DIN": "Consumer Discretionary",
	"FRBA": "Financials",
	"GCO": "Consumer Discretionary",
	"CYH": "Health Care",
	"MGPI": "Consumer Staples",
	"OABI": "Health Care",
	"RLGT": "Industrials",
	"QUIK": "Information Technology",
	"LYEL": "Health Care",
	"MCFT": "Industrials",
	"AIRS": "Health Care",
	"XFOR": "Health Care",
	"ISTR": "Financials",
	"TBRG": "Information Technology",
	"OPAL": "Utilities",
	"XPER": "Information Technology",
	"CLMB": "Information Technology",
	"REPL": "Health Care",
	"QUAD": "Consumer Discretionary",
	"GSIT": "Information Technology",
	"ENTA": "Health Care",
	"NATR": "Health Care",
	"VMD": "Health Care",
	"HVT": "Consumer Discretionary",
	"FMAO": "Financials",
	"NC": "Energy",
	"TACO": "Financials",
	"GBLI": "Financials",
	"RILY": "Financials",
	"TSSI": "Consumer Discretionary",
	"CZNC": "Financials",
	"SOR": "Financials",
	"MPTI": "Information Technology",
	"AVIR": "Health Care",
	"DCTH": "Health Care",
	"VSTM": "Health Care",
	"PBFS": "Financials",
	"AVBC": "Financials",
	"VUZI": "Information Technology",
	"ACCO": "Consumer Discretionary",
	"ORBS": "Other",
	"GNE": "Utilities",
	"MTRX": "Consumer Discretionary",
	"PBYI": "Health Care",
	"CDZI": "Utilities",
	"CLPT": "Health Care",
	"LWAY": "Consumer Staples",
	"PLBC": "Financials",
	"PKBK": "Financials",
	"MCI": "Financials",
	"SAR": "Financials",
	"LE": "Consumer Discretionary",
	"LRMR": "Health Care",
	"RNGR": "Energy",
	"TLS": "Information Technology",
	"NL": "Materials",
	"SSSS": "Financials",
	"PALI": "Health Care",
	"FRST": "Financials",
	"RGNX": "Health Care",
	"PMO": "Financials",
	"BNED": "Consumer Discretionary",
	"HLLY": "Consumer Discretionary",
	"PCB": "Financials",
	"RMNI": "Consumer Discretionary",
	"NMRA": "Health Care",
	"USNA": "Health Care",
	"MSB": "Industrials",
	"MLP": "Financials",
	"PPT": "Financials",
	"CUB": "Industrials",
	"MVBF": "Financials",
	"IRD": "Health Care",
	"FENC": "Health Care",
	"WEYS": "Consumer Staples",
	"SIGA": "Health Care",
	"FWDI": "Industrials",
	"RPAY": "Consumer Discretionary",
	"BCML": "Financials",
	"VGZ": "Materials",
	"USCB": "Financials",
	"NECB": "Financials",
	"MASS": "Industrials",
	"SLP": "Information Technology",
	"CION": "Financials",
	"WSBF": "Financials",
	"ORGO": "Health Care",
	"AVBH": "Financials",
	"LTRX": "Communication Services",
	"ARTNA": "Utilities",
	"BGS": "Consumer Staples",
	"EDIT": "Health Care",
	"NWFL": "Financials",
	"CHMG": "Financials",
	"DMRC": "Information Technology",
	"RM": "Financials",
	"WNC": "Industrials",
	"IVVD": "Health Care",
	"TCI": "Real Estate",
	"CV": "Health Care",
	"DMAC": "Health Care",
	"LCTX": "Health Care",
	"STRT": "Consumer Discretionary",
	"NAUT": "Industrials",
	"AENT": "Consumer Discretionary",
	"RCKT": "Health Care",
	"CMTG": "Financials",
	"ABEO": "Health Care",
	"FNLC": "Financials",
	"SBC": "Health Care",
	"AIRJ": "Industrials",
	"FWRD": "Industrials",
	"IMRX": "Health Care",
	"ELMD": "Health Care",
	"AII": "Financials",
	"PINE": "Real Estate",
	"TTGT": "Communication Services",
	"TCPC": "Financials",
	"PTLO": "Consumer Discretionary",
	"CXDO": "Communication Services",
	"CARL": "Health Care",
	"FLXS": "Consumer Discretionary",
	"TSBK": "Financials",
	"CABO": "Communication Services",
	"SSP": "Industrials",
	"BKTI": "Information Technology",
	"CZFS": "Financials",
	"EFT": "Financials",
	"SVCO": "Information Technology",
	"CIX": "Consumer Discretionary",
	"RZLT": "Health Care",
	"NUCL": "Materials",
	"SI": "Health Care",
	"SEG": "Consumer Discretionary",
	"ASYS": "Information Technology",
	"PRLD": "Health Care",
	"OFLX": "Industrials",
	"ASLE": "Consumer Discretionary",
	"RDNW": "Information Technology",
	"VALU": "Financials",
	"TENX": "Health Care",
	"GCTS": "Information Technology",
	"LODE": "Industrials",
	"TYGO": "Information Technology",
	"ALCO": "Other",
	"COSO": "Financials",
	"FNKO": "Consumer Discretionary",
	"LVWR": "Consumer Discretionary",
	"FATE": "Health Care",
	"ESOA": "Industrials",
	"NAGE": "Health Care",
	"EU": "Materials",
	"SRZN": "Health Care",
	"FUND": "Financials",
	"FJET": "Consumer Discretionary",
	"ISBA": "Financials",
	"ISSC": "Information Technology",
	"MBI": "Financials",
	"JMSB": "Financials",
	"ELDN": "Health Care",
	"ARMP": "Health Care",
	"RC": "Real Estate",
	"ONIT": "Financials",
	"BRBS": "Financials",
	"OIA": "Financials",
	"PPHC": "Other",
	"CNXU": "Health Care",
	"ARDC": "Financials",
	"PAMT": "Industrials",
	"NREF": "Real Estate",
	"RCKY": "Consumer Discretionary",
	"NUS": "Health Care",
	"OSUR": "Health Care",
	"ACV": "Financials",
	"NCMI": "Consumer Discretionary",
	"FLWS": "Consumer Discretionary",
	"ZNTL": "Health Care",
	"OPTU": "Communication Services",
	"NODK": "Financials",
	"HCKT": "Consumer Discretionary",
	"PNRG": "Energy",
	"XPOF": "Consumer Discretionary",
	"HRZN": "Financials",
	"HUMA": "Health Care",
	"FVCB": "Financials",
	"UIS": "Information Technology",
	"NXDT": "Real Estate",
	"FCCO": "Financials",
	"FNRN": "Financials",
	"AKBA": "Health Care",
	"MIN": "Financials",
	"SENS": "Health Care",
	"MYFW": "Financials",
	"AIRO": "Industrials",
	"TG": "Industrials",
	"REI": "Energy",
	"CNDT": "Consumer Discretionary",
	"RWAY": "Financials",
	"OVLY": "Financials",
	"ACRE": "Real Estate",
	"SGHT": "Health Care",
	"BRT": "Real Estate",
	"HBB": "Consumer Discretionary",
	"SABS": "Health Care",
	"SITC": "Real Estate",
	"AVXL": "Health Care",
	"FC": "Consumer Discretionary",
	"LPRO": "Financials",
	"NVCT": "Health Care",
	"MKTW": "Information Technology",
	"MMT": "Financials",
	"FDBC": "Financials",
	"WNEB": "Financials",
	"MGNX": "Health Care",
	"TARA": "Health Care",
	"SCM": "Financials",
	"FOSL": "Consumer Discretionary",
	"TRDA": "Health Care",
	"ESCA": "Consumer Discretionary",
	"CIA": "Financials",
	"ZIP": "Information Technology",
	"FRAF": "Financials",
	"MCR": "Financials",
	"JAKK": "Consumer Discretionary",
	"LEE": "Consumer Discretionary",
	"QSI": "Industrials",
	"EAF": "Energy",
	"CLW": "Materials",
	"CNTX": "Health Care",
	"PPIH": "Industrials",
	"USAU": "Materials",
	"SLNH": "Information Technology",
	"AREC": "Energy",
	"PCYO": "Utilities",
	"PNNT": "Financials",
	"ATLO": "Financials",
	"HWBK": "Financials",
	"CHRS": "Health Care",
	"ALXO": "Health Care",
	"ECC           ": "Financials",
	"CMRC": "Information Technology",
	"TBCH": "Communication Services",
	"LAW": "Information Technology",
	"CPZ": "Financials",
	"FXNC": "Financials",
	"ASUR": "Information Technology",
	"SMRT": "Information Technology",
	"FUNC": "Financials",
	"FHTX": "Health Care",
	"LENZ": "Health Care",
	"CDXS": "Industrials",
	"TKNO": "Health Care",
	"MNTK": "Utilities",
	"YDES": "Health Care",
	"TWIN": "Industrials",
	"OSG": "Financials",
	"RELL": "Information Technology",
	"MITT": "Real Estate",
	"BPRN": "Financials",
	"SNFCA": "Financials",
	"POWW": "Industrials",
	"REFI": "Real Estate",
	"CFFI": "Financials",
	"OPRT": "Financials",
	"ARL": "Real Estate",
	"LCNB": "Financials",
	"APC": "Energy",
	"RGCO": "Utilities",
	"ALEC": "Health Care",
	"OBIO": "Health Care",
	"LOVE": "Consumer Discretionary",
	"FTF": "Financials",
	"WHWK": "Health Care",
	"NKTX": "Health Care",
	"VYGR": "Health Care",
	"IKT": "Health Care",
	"CAMP": "Other",
	"VABK": "Financials",
	"NERV": "Health Care",
	"LMNR": "Consumer Staples",
	"OVBC": "Financials",
	"STRS": "Real Estate",
	"RXST": "Health Care",
	"PEBK": "Financials",
	"MFIN": "Financials",
	"AP": "Industrials",
	"AVNW": "Information Technology",
	"VENU": "Consumer Discretionary",
	"CRBU": "Health Care",
	"KLTR": "Information Technology",
	"ANGI": "Consumer Discretionary",
	"RNA": "Health Care",
	"FBLA": "Financials",
	"LIEN": "Financials",
	"EVI": "Consumer Discretionary",
	"BZAI": "Financials",
	"HDSN": "Consumer Discretionary",
	"KROS": "Health Care",
	"TPVG": "Consumer Discretionary",
	"FSBW": "Financials",
	"KULR": "Information Technology",
	"NKSH": "Financials",
	"KINS": "Financials",
	"LFMD": "Health Care",
	"ACH": "Health Care",
	"SRI": "Consumer Discretionary",
	"SPOK": "Communication Services",
	"JACK": "Consumer Discretionary",
	"GORO": "Materials",
	"SMTI": "Health Care",
	"CMT": "Industrials",
	"CNTN": "Health Care",
	"III": "Consumer Discretionary",
	"MPAA": "Consumer Discretionary",
	"PDEX": "Health Care",
	"VTN": "Financials",
	"EFSI": "Financials",
	"INSG": "Communication Services",
	"INTT": "Industrials",
	"ANNA": "Energy",
	"CPSS": "Financials",
	"LUCD": "Health Care",
	"CMTV": "Financials",
	"GWRS": "Utilities",
	"IMMR": "Information Technology",
	"TONX": "Consumer Discretionary",
	"GENC": "Industrials",
	"RNAC": "Health Care",
	"MRBK": "Financials",
	"UTMD": "Health Care",
	"IMDX": "Health Care",
	"MVIS": "Information Technology",
	"INBK": "Financials",
	"OPBK": "Financials",
	"SMHI": "Consumer Discretionary",
	"GPRO": "Consumer Discretionary",
	"EXOD": "Financials",
	"SGC": "Consumer Discretionary",
	"FCAP": "Financials",
	"AOMR": "Financials",
	"BRR": "Financials",
	"KPTI": "Health Care",
	"MNTS": "Industrials",
	"IMUX": "Health Care",
	"ALTG": "Industrials",
	"STXS": "Health Care",
	"INSE": "Information Technology",
	"KVHI": "Information Technology",
	"ELTX": "Health Care",
	"FT": "Financials",
	"TNXP": "Health Care",
	"RMAX": "Financials",
	"PMTS": "Consumer Discretionary",
	"TLSI": "Health Care",
	"RFIL": "Information Technology",
	"CPSH": "Consumer Discretionary",
	"EGAN": "Information Technology",
	"TMCI": "Health Care",
	"SND": "Industrials",
	"CZWI": "Financials",
	"ANIK": "Health Care",
	"JILL": "Consumer Discretionary",
	"EMBC": "Health Care",
	"LCUT": "Consumer Discretionary",
	"VATE": "Industrials",
	"VERI": "Information Technology",
	"FINW": "Financials",
	"SEVN": "Real Estate",
	"RDIB": "Consumer Discretionary",
	"BMEZ": "Financials",
	"KRRO": "Health Care",
	"AMPY": "Energy",
	"RICK": "Consumer Discretionary",
	"KRMD": "Health Care",
	"TRAK": "Information Technology",
	"MDV": "Real Estate",
	"TGEN": "Industrials",
	"CHPT": "Consumer Discretionary",
	"CVGI": "Consumer Discretionary",
	"ONEW": "Consumer Discretionary",
	"ARTV": "Health Care",
	"UNCY": "Health Care",
	"SLQT": "Financials",
	"PESI": "Industrials",
	"LFCR": "Health Care",
	"TBI": "Consumer Discretionary",
	"SJT": "Energy",
	"KGEI": "Energy",
	"MPV": "Financials",
	"AMTX": "Industrials",
	"EARN": "Real Estate",
	"CFBK": "Financials",
	"ABOS": "Health Care",
	"FF": "Industrials",
	"INFU": "Health Care",
	"COOK": "Consumer Discretionary",
	"JELD": "Materials",
	"CBFV": "Financials",
	"HQI": "Consumer Discretionary",
	"FOA": "Financials",
	"EQ": "Health Care",
	"ESP": "Information Technology",
	"ELME": "Real Estate",
	"DTIL": "Health Care",
	"NLOP": "Real Estate",
	"BCBP": "Financials",
	"STRW": "Real Estate",
	"EBMT": "Financials",
	"PED": "Energy",
	"INGN": "Health Care",
	"EPSN": "Energy",
	"RBKB": "Financials",
	"DOMO": "Information Technology",
	"QTTB": "Health Care",
	"WALD": "Consumer Discretionary",
	"LARK": "Financials",
	"OWLT": "Industrials",
	"APYX": "Health Care",
	"THRY": "Consumer Discretionary",
	"TNYA": "Health Care",
	"TAYD": "Industrials",
	"BHR": "Real Estate",
	"SMID": "Industrials",
	"BVFL": "Financials",
	"WW": "Consumer Discretionary",
	"CMTL": "Information Technology",
	"DERM": "Health Care",
}